<?php

/**
 * BaseService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $url
 * @property string $description
 * @property Doctrine_Collection $Repositories
 * @property Doctrine_Collection $Service
 * @property Doctrine_Collection $RepoServs
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getUrl()          Returns the current record's "url" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method Doctrine_Collection getRepositories() Returns the current record's "Repositories" collection
 * @method Doctrine_Collection getService()      Returns the current record's "Service" collection
 * @method Doctrine_Collection getRepoServs()    Returns the current record's "RepoServs" collection
 * @method Service             setName()         Sets the current record's "name" value
 * @method Service             setUrl()          Sets the current record's "url" value
 * @method Service             setDescription()  Sets the current record's "description" value
 * @method Service             setRepositories() Sets the current record's "Repositories" collection
 * @method Service             setService()      Sets the current record's "Service" collection
 * @method Service             setRepoServs()    Sets the current record's "RepoServs" collection
 * 
 * @package    orinoco
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('url', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Repository as Repositories', array(
             'refClass' => 'RepoServ',
             'local' => 'service_id',
             'foreign' => 'repository_id'));

        $this->hasMany('QltyServ as Service', array(
             'local' => 'id',
             'foreign' => 'service_id'));

        $this->hasMany('RepoServ as RepoServs', array(
             'local' => 'id',
             'foreign' => 'service_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}