<?php

/**
 * BaseRepoServ
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $service_id
 * @property integer $repository_id
 * @property Service $Service
 * @property Repository $Repository
 * 
 * @method integer    getServiceId()     Returns the current record's "service_id" value
 * @method integer    getRepositoryId()  Returns the current record's "repository_id" value
 * @method Service    getService()       Returns the current record's "Service" value
 * @method Repository getRepository()    Returns the current record's "Repository" value
 * @method RepoServ   setServiceId()     Sets the current record's "service_id" value
 * @method RepoServ   setRepositoryId()  Sets the current record's "repository_id" value
 * @method RepoServ   setService()       Sets the current record's "Service" value
 * @method RepoServ   setRepository()    Sets the current record's "Repository" value
 * 
 * @package    orinoco
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRepoServ extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('repo_serv');
        $this->hasColumn('service_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('repository_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Service', array(
             'local' => 'service_id',
             'foreign' => 'id'));

        $this->hasOne('Repository', array(
             'local' => 'repository_id',
             'foreign' => 'id'));
    }
}