<?php

/**
 * BaseQuality
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Quality
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getQuality()     Returns the current record's "Quality" collection
 * @method Quality             setName()        Sets the current record's "name" value
 * @method Quality             setDescription() Sets the current record's "description" value
 * @method Quality             setQuality()     Sets the current record's "Quality" collection
 * 
 * @package    orinoco
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuality extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quality');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('QltyServ as Quality', array(
             'local' => 'id',
             'foreign' => 'quality_id'));
    }
}