<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Queries
 * @property Doctrine_Collection $Plans
 * @property Doctrine_Collection $Repos
 * 
 * @method Doctrine_Collection getQueries() Returns the current record's "Queries" collection
 * @method Doctrine_Collection getPlans()   Returns the current record's "Plans" collection
 * @method Doctrine_Collection getRepos()   Returns the current record's "Repos" collection
 * @method User                setQueries() Sets the current record's "Queries" collection
 * @method User                setPlans()   Sets the current record's "Plans" collection
 * @method User                setRepos()   Sets the current record's "Repos" collection
 * 
 * @package    orinoco
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfGuardUser
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Query as Queries', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Plan as Plans', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Repository as Repos', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}