repository:
  class: sfDoctrineRouteCollection
  options:
    model:                Repository
    module:               Repository
    prefix_path:          /Repository
    column:               id
    with_wildcard_routes: true

service:
  class: sfDoctrineRouteCollection
  options:
    model:                Service
    module:               Service
    prefix_path:          /Service
    column:               id
    with_wildcard_routes: true

plan:
  class: sfDoctrineRouteCollection
  options:
    model:                Plan
    module:               Plan
    prefix_path:          /Plan
    column:               id
    with_wildcard_routes: true

query:
  class: sfDoctrineRouteCollection
  options:
    model:                Query
    module:               Query
    prefix_path:          /Query
    column:               id
    with_wildcard_routes: true

user:
  class: sfDoctrineRouteCollection
  options:
    model:                User
    module:               User
    prefix_path:          /User
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
