<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/22 18:22:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=orinocodb',
  'username' => 'adminorinoco',
  'password' => '0r1n0c0',
  'name' => 'doctrine',
)),);
