<?php

/**
 * PlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plan');
    }
}