<?php

/**
 * QltyServTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QltyServTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QltyServTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QltyServ');
    }
}