<?php

/**
 * QualityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QualityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QualityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quality');
    }
}