<?php

/**
 * RepositoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RepositoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RepositoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Repository');
    }
}