generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Repository
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          repository
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: List of Repositories
      filter:  ~
      form:    ~
      edit:    
        title: Editing Repository %%name%% of %%user%%
      new:     
        title: New Repository
