generator:
  class: sfDoctrineGenerator
  param:
    model_class:           User
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
        title: List of Users
        display: [ =username, first_name, last_name, email_address, is_active ]
      filter:
        display: [ =username, first_name, last_name, email_address, is_active ]
      edit:    
        title: Editing %%username%%
        display: [ first_name, last_name, email_address, username, sex, fecha_nac, academic, password, is_active, is_super_admin ]  
      new:
        title: New User
        
        
